#! /bin/bash
read -r -p "Are you sure? [Y/n] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
	echo "----------------------------------------------------"
	echo "Building production assets...";
	echo "----------------------------------------------------"
	npm run build-prod
	echo " "
	echo " "
	echo "----------------------------------------------------"
    echo "Pushing files to mhweiner.com...";
    echo "----------------------------------------------------"
	rsync -avH --delete --exclude '.htaccess' --exclude '.idea' --exclude 'yarn.lock' --exclude 'webpack.config.js' --exclude 'raw_assets' --exclude '.git' --exclude 'node_modules' --exclude 'devServer.js' --exclude 'npm-debug*' --exclude 'deploy' --exclude 'ReactWebApp' ./ root@mhweiner.com:/var/www/mhweiner/
    echo "----------------------------------------------------"
    echo "Build complete. ^_^";
    echo "----------------------------------------------------"
else
	exit
fi