#! /bin/bash
read -r -p "Are you sure? [Y/n] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
	echo "----------------------------------------------------"
	echo "Building production assets...";
	echo "----------------------------------------------------"
	npm run build-prod
	echo " "
	echo " "
	echo "----------------------------------------------------"
    echo "Pushing files to mhweiner.com...";
    echo "----------------------------------------------------"
	rsync -avH --delete www_static_dist root@mhweiner.com:/opt/mhweiner/.
    echo "----------------------------------------------------"
    echo "Build complete. ^_^";
    echo "----------------------------------------------------"
else
	exit
fi
